Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/DodajRezervaciju.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tickets4You.Models;
using Cassandra;

namespace Tickets4You.Pages
{
    public class DodajRezervacijuModel : PageModel
    {
        public string username;
        public string sport;
        public string home;
        public string away;
        public DateTime date;
        public Korisnik LogovaniKorisnik;
        public Utakmica utakmica;

        [BindProperty]
        public string tribina_cena { get; set; }

        [BindProperty]
        public string racun { get; set; }
        public void OnGet(string sport, string home, string away, DateTime date, string username)
        {
            char[] letters = sport.ToCharArray();
            letters[0] = char.ToLower(letters[0]);
            this.sport = new string(letters);
            this.home = home;
            this.away = away;
            this.date = date;
            this.username = username;
        }

        public async Task<IActionResult> Korisnik()
        {
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command = "SELECT * FROM korisnik WHERE username = '" + username + "';";

            var results = session.Execute(command);

            foreach (var result in results)
            {
                LogovaniKorisnik = new Korisnik(result.GetValue<String>("username"), result.GetValue<String>("password"), result.GetValue<String>("gmail"));
            }

            return new OkResult();
        }

        public async Task<IActionResult> Utakmica()
        {
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command = "SELECT * FROM utakmica WHERE sport = '" + sport + "' AND domacin = '" + home + "' AND gost = '" + away + "' AND datum = '" + new LocalDate(date.Year, date.Month, date.Day) + "';";

            var results = session.Execute(command);

            foreach(var result in results)
            {
                LocalDate ld = result.GetValue<LocalDate>("datum");
                DateTime dt = new DateTime(ld.Year, ld.Month, ld.Day);
                utakmica = new Utakmica(result.GetValue<String>("sport"), result.GetValue<String>("domacin"),
                   result.GetValue<String>("gost"), dt,
                   result.GetValue<int>("broj_slobodnih_mesta_sever"), result.GetValue<int>("broj_slobodnih_mesta_jug"),
                   result.GetValue<int>("broj_slobodnih_mesta_istok"), result.GetValue<int>("broj_slobodnih_mesta_zapad"),
                   result.GetValue<int>("cena_sever"), result.GetValue<int>("cena_jug"),
                   result.GetValue<int>("cena_istok"), result.GetValue<int>("cena_zapad"),
                   result.GetValue<String>("vreme"));
            }

            return new OkResult();
        }

        public async Task<IActionResult> OnPostAsync(string sport, string home, string away, DateTime date, string username)
        {
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command3 = "SELECT * FROM korisnik WHERE username = '" + username + "';";

            var results = session.Execute(command3);

            foreach (var result in results)
            {
                LogovaniKorisnik = new Korisnik(result.GetValue<String>("username"), result.GetValue<String>("password"), result.GetValue<String>("gmail"));
            }

            string command4 = "SELECT * FROM utakmica WHERE sport = '" + sport + "' AND domacin = '" + home + "' AND gost = '" + away + "' AND datum = '" + new LocalDate(date.Year, date.Month, date.Day) + "';";

            results = session.Execute(command4);

            foreach (var result in results)
            {
                LocalDate ld = result.GetValue<LocalDate>("datum");
                DateTime dt = new DateTime(ld.Year, ld.Month, ld.Day);
                utakmica = new Utakmica(result.GetValue<String>("sport"), result.GetValue<String>("domacin"),
                   result.GetValue<String>("gost"), dt,
                   result.GetValue<int>("broj_slobodnih_mesta_sever"), result.GetValue<int>("broj_slobodnih_mesta_jug"),
                   result.GetValue<int>("broj_slobodnih_mesta_istok"), result.GetValue<int>("broj_slobodnih_mesta_zapad"),
                   result.GetValue<int>("cena_sever"), result.GetValue<int>("cena_jug"),
                   result.GetValue<int>("cena_istok"), result.GetValue<int>("cena_zapad"),
                   result.GetValue<String>("vreme"));
            }

            string serial_number = CalculateSerial();
            object[] values = tribina_cena.Split('-');

            LocalDate locd = new LocalDate(utakmica.datum.Year, utakmica.datum.Month, utakmica.datum.Day);

            string command = "INSERT INTO karta(username, serial_number, sport, domacin, gost, datum, cena, racun, tribina) " +
                "VALUES ('" + LogovaniKorisnik.username + "', '" + serial_number + "', '" + utakmica.sport + "', '"
                + utakmica.domacin + "', '" + utakmica.gost + "', '" + locd + "', " + Convert.ToInt32(values[1]) + ", '"
                + racun + "', '" + values[0].ToString() + "');";

            session.Execute(command);

            string command2 = "";

            switch(values[0].ToString())
            {
                case "sever":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_sever = " + (utakmica.bsm_sever-1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                case "jug":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_jug = " + (utakmica.bsm_jug - 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                case "istok":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_istok = " + (utakmica.bsm_istok - 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                case "zapad":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_zapad = " + (utakmica.bsm_zapad - 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                default:
                    break;
            }

            session.Execute(command2);

            return RedirectToPage("/PocetnaZaKorisnika", new { username = LogovaniKorisnik.username });
        }

        public string CalculateSerial()
        {
            string s = "";
            char[] user_let = LogovaniKorisnik.username.ToCharArray();
            s += (DateTime.Today.Hour * DateTime.Today.Minute + DateTime.Today.Second);
            s += DateTime.Today.ToString("yyyy_MM_dd");
            for (int i = 0; i < user_let.Length / 2; i++)
                s += (user_let[i] + "" + user_let[user_let.Length - 1 - i]);
            return s;
        }
    }
}

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Tickets4You.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tickets4You.Models;
using Cassandra;

namespace Tickets4You.Pages
{
    public class IndexModel : PageModel
    {

        public Korisnik korisnik;

        [BindProperty]
        public string KorisnickoIme { get; set; }

        [BindProperty]
        public string Sifra { get; set; }

        public bool Greska = false;

        public void OnGet()
        {
            
        }
        public async Task<IActionResult> OnPostAsync()
        {
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command = "SELECT * FROM korisnik WHERE username = '" + KorisnickoIme +"';";

            var results = session.Execute(command);

            if (results == null)
            {
                Greska = true;
                return Page();
            }
            else
            {

                foreach (var result in results)
                {
                    korisnik = new Korisnik(result.GetValue<String>("username"), result.GetValue<String>("password"), result.GetValue<String>("gmail"));
                }

                if (korisnik.password == Sifra)
                    return RedirectToPage("/PocetnaZaKorisnika", new { username = korisnik.username });
                else
                {
                    Greska = true;
                    return Page();
                }
            }
        }
    }
}

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/MojeRezervacije.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cassandra;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Tickets4You.Models;

namespace Tickets4You.Pages
{
    public class MojeRezervacijeModel : PageModel
    {
        public string username;
        public Korisnik LogovaniKorisnik;
        public List<Karta> karte;
        public Utakmica utakmica;
        public Karta karta;
        public void OnGet(string username)
        {
            this.username = username;
        }

        public async Task<IActionResult> Korisnik()
        {
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command = "SELECT * FROM korisnik WHERE username = '" + username + "';";

            var results = session.Execute(command);

            foreach (var result in results)
            {
                LogovaniKorisnik = new Korisnik(result.GetValue<String>("username"), result.GetValue<String>("password"), result.GetValue<String>("gmail"));
            }

            return new OkResult();
        }

        public async Task<IActionResult> Rezervacije()
        {
            karte = new List<Karta>();
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command = "SELECT * FROM karta WHERE username = '" + username + "';";

            var results = session.Execute(command);
            foreach (var result in results)
            {
                LocalDate ld = result.GetValue<LocalDate>("datum");
                DateTime dt = new DateTime(ld.Year, ld.Month, ld.Day);
                karte.Add(new Karta(result.GetValue<String>("username"), result.GetValue<String>("serial_number"),
                    result.GetValue<String>("sport"), result.GetValue<String>("domacin"),
                    result.GetValue<String>("gost"), dt,
                    result.GetValue<int>("cena"), result.GetValue<String>("racun"),
                    result.GetValue<String>("tribina")));
            }

            return new OkResult();
        }

        public async Task<IActionResult> OnGetOtkaziAsync(string serial_number, string username, string sport, string domacin, string gost, DateTime datum)
        {
            var cluster = Cluster.Builder()
                .AddContactPoint("127.0.0.1")
                .Build();

            var session = cluster.Connect("tickets4you");

            string command3 = "SELECT * FROM karta WHERE serial_number = '" + serial_number + "' AND username = '" + username + "';";

            var results = session.Execute(command3);
            string tribina = "";
            
            foreach(var result in results)
            {
                LocalDate ld = result.GetValue<LocalDate>("datum");
                DateTime dt = new DateTime(ld.Year, ld.Month, ld.Day);
                karta = new Karta(result.GetValue<String>("username"), result.GetValue<String>("serial_number"), result.GetValue<String>("sport"),
                    result.GetValue<String>("domacin"), result.GetValue<String>("gost"), dt,
                    result.GetValue<Int32>("cena"), result.GetValue<String>("racun"), result.GetValue<String>("tribina"));
                tribina = result.GetValue<String>("tribina");
            }

            string command4 = "SELECT * FROM utakmica WHERE sport = '" + karta.sport + "' AND domacin = '" + karta.domacin + "' AND gost = '" + karta.gost + "' AND datum = '" + new LocalDate(karta.datum.Year, karta.datum.Month, karta.datum.Day) + "';";

            results = session.Execute(command4);

            foreach (var result in results)
            {
                LocalDate ld = result.GetValue<LocalDate>("datum");
                DateTime dt = new DateTime(ld.Year, ld.Month, ld.Day);
                utakmica = new Utakmica(result.GetValue<String>("sport"), result.GetValue<String>("domacin"),
                   result.GetValue<String>("gost"), dt,
                   result.GetValue<int>("broj_slobodnih_mesta_sever"), result.GetValue<int>("broj_slobodnih_mesta_jug"),
                   result.GetValue<int>("broj_slobodnih_mesta_istok"), result.GetValue<int>("broj_slobodnih_mesta_zapad"),
                   result.GetValue<int>("cena_sever"), result.GetValue<int>("cena_jug"),
                   result.GetValue<int>("cena_istok"), result.GetValue<int>("cena_zapad"),
                   result.GetValue<String>("vreme"));
            }

            string command2 = "";
            LocalDate locd = new LocalDate(utakmica.datum.Year, utakmica.datum.Month, utakmica.datum.Day);

            switch (tribina)
            {
                case "sever":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_sever = " + (utakmica.bsm_sever + 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                case "jug":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_jug = " + (utakmica.bsm_jug + 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                case "istok":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_istok = " + (utakmica.bsm_istok + 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                case "zapad":
                    command2 = "UPDATE utakmica SET broj_slobodnih_mesta_zapad = " + (utakmica.bsm_zapad + 1) + "" +
                        " WHERE sport = '" + utakmica.sport + "' AND domacin = '" + utakmica.domacin
                        + "' AND gost = '" + utakmica.gost + "' AND datum = '" + locd + "';";
                    break;
                default:
                    break;
            }

            session.Execute(command2);

            LocalDate dld = new LocalDate(datum.Year, datum.Month, datum.Day);
            string command = "DELETE FROM karta WHERE serial_number = '" + serial_number + "' AND username = '" + username + "' AND sport = '" + sport + "' AND domacin = '" + domacin + "' AND gost = '" + gost + "' AND datum = '" + dld + "' IF EXISTS; ";

            session.Execute(command);
            return base.RedirectToPage(new { username = username });
        }
    }
}

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/DodajRezervaciju.cshtml
@page
@model Tickets4You.Pages.DodajRezervacijuModel
@{
    ViewData["Title"] = "Dodaj Rezervaciju";
    await Model.Korisnik();
    await Model.Utakmica();
    ViewData["korisnik"] = Model.LogovaniKorisnik.username;
}

<head>
    <link href="~/css/rezervacija.css" rel="stylesheet" />
</head>

<body>
    <div class="cont">
        <div class="container2">
            <div class="naziv-div"><label class="datum-vreme">@Model.utakmica.datum.Day/@Model.utakmica.datum.Month/@Model.utakmica.datum.Year &nbsp;&nbsp;&nbsp;&nbsp; @Model.utakmica.vreme</label><label class="naziv-liga">@Model.utakmica.domacin - : - @Model.utakmica.gost</label></div>
        </div>

        <div class="forma">
            <div class="information">
                <label class="headlines"><b>Trenutno stanje rezervacija:</b></label>
                <label>Broj slobodnih mesta na severnoj tribini: &nbsp; @Model.utakmica.bsm_sever</label>
                <label>Cena karte na severnoj tribini: &nbsp; @Model.utakmica.cena_sever€</label>

                <hr class="sidebar-divider d-none d-md-block col-11">

                <label>Broj slobodnih mesta na južnoj tribini: &nbsp; @Model.utakmica.bsm_jug</label>
                <label>Cena karte na južnoj tribini: &nbsp; @Model.utakmica.cena_jug€</label>

                <hr class="sidebar-divider d-none d-md-block col-11">

                <label>Broj slobodnih mesta na istočnoj tribini: &nbsp; @Model.utakmica.bsm_istok</label>
                <label>Cena karte na istočnoj tribini: &nbsp; @Model.utakmica.cena_istok€</label>

                <hr class="sidebar-divider d-none d-md-block col-11">

                <label>Broj slobodnih mesta na zapadnoj tribini: &nbsp; @Model.utakmica.bsm_zapad</label>
                <label>Cena karte na zapadnoj tribini: &nbsp; @Model.utakmica.cena_zapad€</label>
            </div>

            <div class="inputs">
                <form method="post">
                    <div class="podatak">
                        <label class="headlines"><b>Izaberite željenu tribinu:</b></label>
                        @{
                            if (Model.utakmica.bsm_sever == 0)
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="sever-@Model.utakmica.cena_sever" asp-for="@Model.tribina_cena" disabled="disabled" />&nbsp;&nbsp;Sever</label>
                            }
                            else
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="sever-@Model.utakmica.cena_sever" asp-for="@Model.tribina_cena" />&nbsp;&nbsp;Sever</label>
                            }
                            if (Model.utakmica.bsm_jug == 0)
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="jug-@Model.utakmica.cena_jug" asp-for="@Model.tribina_cena" disabled="disabled" />&nbsp;&nbsp;Jug</label>
                            }
                            else
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="jug-@Model.utakmica.cena_jug" asp-for="@Model.tribina_cena" />&nbsp;&nbsp;Jug</label>
                            }
                            if (Model.utakmica.bsm_istok == 0)
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="istok-@Model.utakmica.cena_istok" asp-for="@Model.tribina_cena" disabled="disabled" />&nbsp;&nbsp;istok</label>
                            }
                            else
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="istok-@Model.utakmica.cena_istok" asp-for="@Model.tribina_cena" />&nbsp;&nbsp;istok</label>
                            }
                            if (Model.utakmica.bsm_zapad == 0)
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="zapad-@Model.utakmica.cena_zapad" asp-for="@Model.tribina_cena" disabled="disabled" />&nbsp;&nbsp;Zapad</label>
                            }
                            else
                            {
                                <label class="radio-label"><input type="radio" name="tribina_cena" value="zapad-@Model.utakmica.cena_zapad" asp-for="@Model.tribina_cena" />&nbsp;&nbsp;Zapad</label>
                            }
                        }
                    </div>

                    <div class="podatak">
                        <label class="headlines"><b>Racun za uplatu:</b></label>
                        <input type="text" name="racun" asp-for="@Model.racun" onkeydown="Potvrdi(this)" onchange="Potvrdi(this)"/>
                    </div>

                    <div class="potvrda">
                        <button id="potvrdi" class="btn btn-success" asp-route-sport="@Model.utakmica.sport" asp-route-home="@Model.utakmica.domacin" asp-route-away="@Model.utakmica.gost" asp-route-date="@Model.utakmica.datum" asp-route-username="@Model.LogovaniKorisnik.username" disabled="disabled">Potvrdi</button>
                        <a class="btn btn-warning" asp-route="/PocetnaZaKorisnika" asp-route-username="@Model.LogovaniKorisnik.username">Otkazi</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <script src="~/js/rezervacija.js"></script>
</body>

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "LogIn";
}

<head>
    <link href="~/css/Login.css" rel="stylesheet" />
</head>

<body>
    <div id="lige">
        <div class="container liga">

            <div class="container2">
                <div class="naziv-div"><label class="naziv-liga">Uloguj se</label></div>
            </div>
            <div class="utakmice row">
                <div class="utakmica">
                    <form class=" validate-form" method="post">
                        <div class=" validate-input" data-validate="Unesi korisničko ime">
                            <input type="text" name="korisnickoime" asp-for="@Model.KorisnickoIme" placeholder="Korisničko ime">

                        </div>

                        <div class="validate-input" data-validate="Unesi lozinku">
                            <input type="password" name="sifra" asp-for="@Model.Sifra" placeholder="Lozinka">

                        </div>
                        <br />
                        @if (Model.Greska)
                        {
                            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                <strong>Pogrešno korisničko ime ili lozinka</strong>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        }
                        <div>
                            <button class="btn btn-primary">Uloguj se</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="~/js/NovaLiga.js"></script>
</body>

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/MojeRezervacije.cshtml
@page
@model Tickets4You.Pages.MojeRezervacijeModel
@{
    ViewData["Title"] = "MojeRezervacije";
    await Model.Korisnik();
    await Model.Rezervacije();
    ViewData["korisnik"] = Model.LogovaniKorisnik.username;
}

<head>
    <link href="~/css/main.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>

</head>

<body>
    <div id="lige">
        <div class="container liga">
            <div class="container2">
                <div class="naziv-div"><label class="naziv-liga">Moje rezervacije</label></div>
            </div>
            <div class="utakmice">

                @foreach (Models.Karta k in Model.karte)
                {
                    <div class="utakmica row">
                        <div class="datum-vreme-div"><label class="datum-vreme">@k.datum</label></div>
                        <div class="timovi col-2"><label class="home">@k.domacin</label> - <label class="away">@k.gost</label></div>
                        <div class="cena">@k.cena evra</div>
                        <div class="tribina">@k.tribina</div>
                        <div>
                            <a type="button" class="btn btn-warning" asp-route-username="@Model.LogovaniKorisnik.username" asp-route-serial_number="@k.serial_number" asp-route-sport="@k.sport" asp-route-domacin="@k.domacin" asp-route-gost="@k.gost" asp-route-datum="@k.datum" asp-page="/IzmenaRezervacije">Izmeni rezervaciju</a>
                            <button id="@k.serial_number" type="button" class="btn btn-danger" data-toggle="modal" data-placement="right" title="Otkazi rezervaciju!" data-target="#deleteModal@{@k.serial_number;}">Otkaži rezervaciju</button>
                        </div>
                    </div>


                    <hr class="sidebar-divider d-none d-md-block col-11">
                    <div class="modal fade" id="deleteModal@{@k.serial_number;}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header odjava">
                                    <h5 class="modal-title" id="exampleModalLabel">Potvrda otkazivanja rezervacije</h5>
                                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">×</span>
                                    </button>
                                </div>
                                <div class="modal-body odjava">Da li ste sigurni da želite da otkažete rezervaciju?</div>
                                <div class="modal-footer odjava">

                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Otkaži</button>
                                    <a class="btn btn-primary" asp-route-serial_number="@k.serial_number" asp-route-username="@Model.LogovaniKorisnik.username" asp-route-sport="@k.sport" asp-route-domacin="@k.domacin" asp-route-gost="@k.gost" asp-route-datum="@k.datum" asp-page-handler="Otkazi">Potvrdi</a>

                                </div>
                            </div>
                        </div>
                    </div>
                }

            </div>
        </div>

    </div>
</body>

Aplikacija/Tickets4You/Tickets4You/Tickets4You/Pages/PocetnaZaKorisnika.cshtml
@page
@model Tickets4You.Pages.PocetnaZaKorisnikaModel
@{
    ViewData["Title"] = "PocetnaZaKorisnika";
    await Model.Korisnik();
    await Model.Utakmice();
    ViewData["korisnik"] = Model.LogovaniKorisnik.username;
}

<head>
    <link href="~/css/index.css" rel="stylesheet" />


</head>

<body>
    <div id="lige">
            @foreach (string sp in Model.sportovi)
            {
                <div class="container liga">
                    <div class="container2">
                        <div class="naziv-div"><label class="naziv-liga">@sp</label></div>
                    </div>
                    <div class="utakmice">
                        @foreach (Models.Utakmica u in Model.utakmice)
                        {
                            if (u.sport == sp)
                            {
                                <div class="utakmica row">
                                    <div class="datum-vreme-div col-3"><label class="datum-vreme">@u.datum.Day/@u.datum.Month/@u.datum.Year &nbsp;&nbsp;&nbsp;&nbsp; @u.vreme</label></div>
                                    <div class="timovi col-7"><label class="home">@u.domacin</label><label class="score"> - : - </label> <label class="away">@u.gost</label></div>
                                    <div class="omiljena col-1"><a class="rezervisi btn btn-primary" asp-page="/DodajRezervaciju" asp-route-sport="@u.sport" asp-route-home="@u.domacin" asp-route-away="@u.gost" asp-route-date="@u.datum" asp-route-username="@Model.LogovaniKorisnik.username">Rezerviši</a></div>
                                </div>

                                <hr class="sidebar-divider d-none d-md-block col-11">
                            }
                        }
                    </div>
                </div>
            }
    </div>
</body>